server:
  port: 8083
spring:
  application:
    name: hmdp-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.100.212:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: '#gmrGMR110202'
  rabbitmq:
    host: 115.190.193.236
    username: paperplane
    password: 123456
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 50
        auto-startup: true
        default-requeue-rejected: false
    template:
      mandatory: true
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hmdp.order.entity
logging:
  level:
    root: info
    com.hmdp.order: debug
