server:
  port: 8088
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  tomcat:
    threads:
      max: 1000
    accept-count: 1000
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.100.212:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: '#gmrGMR110202'
  redis:
    cluster:
      nodes:
      - 123.56.100.212:6379
      - 39.97.193.168:6379
      - 115.190.193.236:6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 115.190.193.236
    username: paperplane
    password: 123456
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: false
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1
mybatis-plus:
  type-aliases-package: com.hmdp.entity
logging:
  level:
    com.hmdp: debug
